apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-luboost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luboost
  template:
    metadata:
      labels:
        app: luboost
    spec:
      containers:
        - name: pod-luboost
          image: edichoi/luboost:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-luboost
spec:
  type: NodePort
  selector:
    app: luboost
  ports:
    - nodePort: 30400
      port: 80
      targetPort: 80
